name: NPM Example

on:
  push:
    branches: [ jfrog-poc ]
  pull_request:
    branches: [ jfrog-poc ]
  workflow_dispatch:
    branches: [ jfrog-poc ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: chekout git repo
      uses: actions/checkout@v2
    - name: use Jfrog CLI to publish to NPM
      uses: jfrog/setup-jfrog-cli@v2
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Publish to NPM
      run: |
           cd npm-example
           jfrog --version
           jfrog c add testaccount --artifactory-url ${{ secrets.TESTARTIFACTORY}} --user ${{ secrets.TESTUSER }} --access-token ${{ secrets.TESTTOKEN }}
           echo "Current Working location $(pwd)"
           jfrog c show
           jfrog rt npmi npm --build-name my-npm-build-2 --build-number 123 
           jfrog rt bce my-npm-build-2 123
           jfrog rt bag my-npm-build-2 123
           jfrog rt npmp npm  --build-name my-npm-build-2 --build-number 123
           jfrog rt bp my-npm-build-2 123

